#!/bin/bash

my_dir="$( cd "$( dirname "$0"  )" && pwd  )"
# put device name here to run fio test for 
# multiple disks in parallel
# example disks=(nvme0n1 nvme1n1 nvme2n1 nvme3n1)
disks=(nvme0n1)

# #another example to run test for even more disks
# #
# disk=""
# dev_prefix=sfdv
# for i in {0..12}
# do
#     disks="${disks} ${dev_prefix}${i}n1"
# done
#

# cpus_allowed?，The number of CPU cores assigned to this parameter is the same as the maximum number of jobs in all I/O patterns. 
# For details, see the description of the cpus_allowed option in the man fio help manual
# example：_cpus_allowed=1,3,5,7,9
_cpus_allowed=''

# fio workloads
workloads=( \
    precond_seq \
    seqwrite \
    seqread \
    precond_rand \
    randwrite \
    randrw \
    randread \
    precond_seq \
    lat_read \
    lat_write \
    )

# change the numbers below to control compressibility
# generated by fio. larger number means higher 
# compressibility 
comp_ratio=${comp_ratio-60}

# below numbers controls the fio workload run time.
# they does not affect the time used for pre-condition
# workloads, like precond_seq and precond_rand
export ramp_time=${ramp_time-60}
export runtime=${runtime-1800}

if [ "${comp_ratio}" != "" ]; 
then
    comp_opt_str=" --buffer_compress_chunk=4k --buffer_compress_percentage=${comp_ratio} "
else 
    comp_opt_str=""
fi

if [ "${_cpus_allowed}" != "" ]; 
then
    cpus_opt_str=" ${_cpus_allowed}"
else
    cpus_opt_str=""
fi

timestamp=`date +%Y%m%d_%H%M%S`
output_dir=${my_dir}/${timestamp}

if [ ! -d "${output_dir}" ]; then mkdir -p ${output_dir}; fi
iostat_dir=${output_dir}/iostat
result_dir=${output_dir}/result
drvinfo_dir=${output_dir}/drvinfo
thermal_dir=${output_dir}/thermal
mkdir -p ${iostat_dir}
mkdir -p ${result_dir}
mkdir -p ${drvinfo_dir}
mkdir -p ${thermal_dir}

source ${my_dir}/functions

collect_sys_info > ${output_dir}/sysinfo.log

for disk in ${disks[@]}
do
    collect_drv_info ${disk} > ${drvinfo_dir}/${disk}_1.info
done

for workload in ${workloads[@]}
do
    iostat_pid_list=""
    thermal_pid_list=""
    fio_pid_list=""
    for disk in ${disks[@]};
    do
        iostat -dxmct 1 ${disk} > ${iostat_dir}/${disk}_${workload}.iostat &
        iostat_pid_list="${iostat_pid_list} $!"
        ${my_dir}/record_thermal.sh /dev/${disk} ${thermal_dir}/${disk}_${workload}.thermal &
        thermal_pid_list="${thermal_pid_list} $!"

        fio ${comp_opt_str} ${cpus_opt_str} \
            --filename=/dev/${disk} \
            --output=${result_dir}/${disk}_${workload}.fio \
            ${my_dir}/jobs/${workload}.fio &
        fio_pid_list="${fio_pid_list} $!"
    done

    wait ${fio_pid_list}
    sync
    kill -9 ${thermal_pid_list}
    kill -9 ${iostat_pid_list}
done

for disk in ${disks[@]}
do
    collect_drv_info ${disk} > ${drvinfo_dir}/${disk}_2.info
done

iostat_to_csv ${iostat_dir} ${disk}
for disk in ${disks[@]}
do
    fio_to_csv ${result_dir} ${disk}
done
consolidate_summary ${result_dir} ${output_dir}
